export type MarketplaceSeedResource = {
  id: string
  title: string
  resource_type: 'lesson_plan' | 'question_bank' | 'engage_game' | 'train_track'
  subject: string
  level: string
  description: string
  price_ghs: number | null
  status: 'draft' | 'pending_review' | 'published' | 'rejected'
  import_count: number
  rating_avg: number
  rating_count: number
  metadata: Record<string, unknown>
  creator_id?: string | null
  institution_id?: string | null
}

/** Demo marketplace resources matching design export copy */
export const MARKETPLACE_DEMO_RESOURCES: MarketplaceSeedResource[] = [
  {
    id: 'a1000000-0000-0000-0000-000000000001',
    title: 'Cell division — full unit plan',
    resource_type: 'lesson_plan',
    subject: 'Biology',
    level: 'JHS 2',
    description:
      'A complete 5-lesson unit on cell division for JHS 2 Biology. Includes mitosis and meiosis, diagrams, 30 assessment questions, and 2 ready-to-host Engage games.',
    price_ghs: null,
    status: 'published',
    import_count: 862,
    rating_avg: 4.9,
    rating_count: 142,
    metadata: {
      creator_name: 'K. Owusu',
      creator_initials: 'KO',
      verified: true,
      featured: true,
      accent: 'teal',
      includes: [
        '5 fully scripted lesson plans',
        '30-question assessment bank',
        '2 Engage games (ready to host)',
        'Mark schemes and answer guides',
      ],
      stats: { lessons: 5, estimated_hours: 3, level: 'JHS 2' },
      content: {
        modules: [
          { id: 'm1', title: 'Introduction to cell division', type: 'reading', content: {}, duration_minutes: 35 },
          { id: 'm2', title: 'Mitosis step by step', type: 'video', content: {}, duration_minutes: 40 },
          { id: 'm3', title: 'Meiosis and variation', type: 'reading', content: {}, duration_minutes: 35 },
          { id: 'm4', title: 'Unit assessment', type: 'quiz', content: {}, duration_minutes: 30 },
          { id: 'm5', title: 'Revision and recap', type: 'flashcards', content: {}, duration_minutes: 20 },
        ],
        thumbnail_color: '#1A8966',
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000002',
    title: 'Algebra blitz — 50Q game',
    resource_type: 'engage_game',
    subject: 'Maths',
    level: 'JHS 3',
    description: 'Fast-paced Engage quiz covering linear equations, factorisation, and word problems. Built for revision weeks and end-of-term review.',
    price_ghs: 5,
    status: 'published',
    import_count: 314,
    rating_avg: 4.7,
    rating_count: 89,
    metadata: {
      creator_name: 'Yaw A.',
      creator_initials: 'YA',
      verified: true,
      featured: true,
      accent: 'navy',
      stats: { questions: 50, estimated_minutes: 45 },
      content: {
        questions: Array.from({ length: 5 }, (_, i) => ({
          id: `q${i + 1}`,
          type: 'mcq' as const,
          text: `Sample algebra question ${i + 1}`,
          options: [
            { label: 'A', text: 'Option A' },
            { label: 'B', text: 'Option B' },
            { label: 'C', text: 'Option C' },
            { label: 'D', text: 'Option D' },
          ],
          correct: 'A',
          correct_multiple: [],
          time_seconds: 30,
          points: 1000,
        })),
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000003',
    title: 'New staff onboarding track',
    resource_type: 'train_track',
    subject: 'Train',
    level: 'All staff',
    description: 'Mandatory onboarding path for new teachers and admin staff. Covers policies, safeguarding, and platform setup.',
    price_ghs: null,
    status: 'published',
    import_count: 421,
    rating_avg: 4.8,
    rating_count: 61,
    metadata: {
      creator_name: 'EduGhana',
      creator_initials: 'EG',
      verified: true,
      featured: true,
      accent: 'violet',
      content: {
        steps: [
          {
            id: 's1',
            title: 'Welcome and policies',
            type: 'reading',
            content: {
              body: 'Welcome to the team. This section covers our core policies, safeguarding expectations, and how we work together.\n\nRead each section carefully before moving on.',
              key_principle: 'Policies protect staff, students, and the institution. Know them before you start.',
              quick_check: { text: 'Who should you contact if you have a safeguarding concern?', options: ['HR only', 'Your line manager or safeguarding lead', 'No one'], correct: 1 },
            },
            duration_minutes: 20,
            is_mandatory: true,
          },
          {
            id: 's2',
            title: 'Safeguarding briefing',
            type: 'video',
            content: { youtube_id: 'dQw4w9WgXcQ', body: 'Watch the safeguarding briefing in full.' },
            duration_minutes: 25,
            is_mandatory: true,
          },
          {
            id: 's3',
            title: 'Platform orientation quiz',
            type: 'quiz',
            content: {
              questions: [
                { text: 'Where do you find your assigned training paths?', options: ['Train module', 'Engage only', 'Email inbox'] },
                { text: 'Who can you ask if you cannot access a path?', options: ['Anyone online', 'Your line manager or HR', 'Nobody'] },
              ],
            },
            duration_minutes: 15,
            is_mandatory: true,
          },
          {
            id: 's4',
            title: 'Line manager sign-off',
            type: 'sign_off',
            content: { policy_text: 'I confirm I have completed onboarding training and understand my responsibilities under school policy.' },
            duration_minutes: 5,
            is_mandatory: true,
          },
        ],
        category: 'Onboarding',
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000004',
    title: 'Physics — Waves & Optics question bank',
    resource_type: 'question_bank',
    subject: 'Physics',
    level: 'SHS 1',
    description: '45 curated questions on waves, reflection, refraction, and lenses. Includes worked solutions for SHS 1 Physics.',
    price_ghs: 8,
    status: 'published',
    import_count: 198,
    rating_avg: 4.6,
    rating_count: 37,
    metadata: {
      creator_name: 'K. Owusu',
      creator_initials: 'KO',
      verified: true,
      featured: false,
      accent: 'amber',
      stats: { questions: 45 },
      content: {
        questions: Array.from({ length: 3 }, (_, i) => ({
          id: `eq${i + 1}`,
          type: 'mcq' as const,
          text: `Waves and optics question ${i + 1}`,
          options: [
            { label: 'A', text: 'Option A' },
            { label: 'B', text: 'Option B' },
          ],
          correct: 'A',
          marks: 2,
        })),
        duration_minutes: 90,
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000005',
    title: 'BECE Math prep — full mock exam set',
    resource_type: 'question_bank',
    subject: 'Maths',
    level: 'BECE',
    description: 'Three full BECE-style maths papers with mark schemes. Aligned to current GES syllabus and past paper patterns.',
    price_ghs: null,
    status: 'published',
    import_count: 1204,
    rating_avg: 4.9,
    rating_count: 203,
    metadata: {
      creator_name: 'EduGhana',
      creator_initials: 'EG',
      verified: true,
      featured: false,
      accent: 'teal',
      stats: { exams: 3, questions: 120 },
      content: {
        questions: [
          { id: 'bece1', type: 'mcq', text: 'BECE sample question 1', options: [{ label: 'A', text: '2' }, { label: 'B', text: '4' }], correct: 'A', marks: 1 },
        ],
        duration_minutes: 120,
        instructions: 'Answer all questions. Show working where required.',
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000006',
    title: 'English comprehension pack — JHS 2',
    resource_type: 'lesson_plan',
    subject: 'English',
    level: 'JHS 2',
    description: 'Six reading passages with comprehension questions, vocabulary builders, and short writing prompts for JHS 2 English.',
    price_ghs: null,
    status: 'published',
    import_count: 556,
    rating_avg: 4.5,
    rating_count: 48,
    metadata: {
      creator_name: 'Abena M.',
      creator_initials: 'AM',
      verified: true,
      featured: false,
      accent: 'teal',
      stats: { lessons: 6, estimated_hours: 4 },
      content: {
        modules: [
          { id: 'e1', title: 'Reading: The market day', type: 'reading', content: {}, duration_minutes: 40 },
          { id: 'e2', title: 'Comprehension quiz', type: 'quiz', content: {}, duration_minutes: 25 },
        ],
        thumbnail_color: '#1A8966',
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000007',
    title: 'Chemistry — Acids and bases unit',
    resource_type: 'lesson_plan',
    subject: 'Chemistry',
    level: 'SHS 1',
    description: 'Four-lesson SHS 1 unit covering pH, neutralisation, and titration basics with practical lab notes.',
    price_ghs: 6,
    status: 'published',
    import_count: 167,
    rating_avg: 4.4,
    rating_count: 29,
    metadata: {
      creator_name: 'Dr. Adjei',
      creator_initials: 'DA',
      verified: true,
      featured: false,
      accent: 'violet',
      stats: { lessons: 4, estimated_hours: 2.5 },
      content: {
        modules: [
          { id: 'c1', title: 'Properties of acids and bases', type: 'reading', content: {}, duration_minutes: 35 },
          { id: 'c2', title: 'pH and indicators', type: 'video', content: {}, duration_minutes: 30 },
        ],
        thumbnail_color: '#2E2886',
      },
    },
  },
  {
    id: 'a1000000-0000-0000-0000-000000000008',
    title: 'ICT basics — typing and safety',
    resource_type: 'train_track',
    subject: 'ICT',
    level: 'JHS 1',
    description: 'Introductory ICT training for JHS students covering keyboard skills, online safety, and responsible device use.',
    price_ghs: null,
    status: 'published',
    import_count: 289,
    rating_avg: 4.6,
    rating_count: 52,
    metadata: {
      creator_name: 'SphereSDS Team',
      creator_initials: 'SS',
      verified: true,
      featured: false,
      accent: 'blue',
      content: {
        steps: [
          { id: 'i1', title: 'Keyboard fundamentals', type: 'video', content: {}, duration_minutes: 20, is_mandatory: true },
          { id: 'i2', title: 'Online safety quiz', type: 'quiz', content: {}, duration_minutes: 15, is_mandatory: true },
        ],
        category: 'Digital literacy',
      },
    },
  },
  {
    id: 'b1000000-0000-0000-0000-000000000001',
    title: 'Cell division — complete unit plan',
    resource_type: 'lesson_plan',
    subject: 'Biology',
    level: 'JHS 2',
    description:
      'A complete 5-lesson unit on cell division for JHS 2 Biology. Includes mitosis and meiosis, diagrams, 30 assessment questions, and 2 ready-to-host Engage games.',
    price_ghs: null,
    status: 'pending_review',
    import_count: 0,
    rating_avg: 0,
    rating_count: 0,
    metadata: {
      creator_name: 'K. Owusu',
      creator_initials: 'KO',
      verified: false,
      attachments: ['Lesson_plans_unit4.pdf', '30Q_assessment_bank'],
    },
  },
  {
    id: 'b1000000-0000-0000-0000-000000000002',
    title: 'Algebra blitz — 50Q Engage game',
    resource_type: 'engage_game',
    subject: 'Maths',
    level: 'JHS 3',
    description: 'Fast-paced Engage quiz covering linear equations, factorisation, and word problems.',
    price_ghs: 5,
    status: 'pending_review',
    import_count: 0,
    rating_avg: 0,
    rating_count: 0,
    metadata: {
      creator_name: 'Yaw A.',
      creator_initials: 'YA',
      verified: false,
    },
  },
  {
    id: 'b1000000-0000-0000-0000-000000000003',
    title: 'New staff onboarding train track',
    resource_type: 'train_track',
    subject: 'Train',
    level: 'All staff',
    description: 'Mandatory onboarding path for new teachers and admin staff.',
    price_ghs: null,
    status: 'pending_review',
    import_count: 0,
    rating_avg: 0,
    rating_count: 0,
    metadata: {
      creator_name: 'EduGhana',
      creator_initials: 'EG',
      verified: false,
    },
  },
]
